[toolchain]
package_manager = "yarn"
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
gkescrow = "6saaps2jtMCng2XxkuBG3Cizvcsfy2LBm8AGicK2NamF"

[programs.localnet]
gkescrow = "6saaps2jtMCng2XxkuBG3Cizvcsfy2LBm8AGicK2NamF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
build = "anchor build"
deploy = "anchor deploy --provider.cluster devnet"
generate-idl = "cp target/idl/gkescrow.json ../src/idl/gkescrow.json"
